version: '3.9'

services:
  web:
    build: .
    command: sh docker/django/entrypoint.sh
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - db
      - redis

  worker:
    build: .
    command: sh docker/celery/worker_entrypoint.sh
    volumes:
      - ./app:/app
    env_file: .env
    depends_on:
      - db
      - redis

  beat:
    build: .
    command: sh docker/celery/beat_entrypoint.sh
    volumes:
      - ./app:/app
    env_file: .env
    depends_on:
      - db
      - redis

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password